name: Deploy main branch
on:
  push:
    branches:
      - main
env:
  CI: true
  SSH_PORT: 22

jobs:
  send-noti:
    runs-on: ubuntu-latest
    name: Send noti to telegram on
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RECEIVER }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "🚀 Start deploy Nested Notation to main 🚀"
  deploy:
    runs-on: ubuntu-latest
    needs: send-noti
    steps:
      - name: Pull code and restart pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME_PROD }}
          port: 22
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            whoami
            pwd
            cd nestednotation
            git pull origin main
            npm install
            pm2 start ecosystem.config.js -f
  send-noti-on-success:
    runs-on: ubuntu-latest
    needs: deploy
    name: Send noti to telegram on success
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RECEIVER }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "✅ Deploy Nested Notation to main successfully ✅"
        
