name: Deploy main branch
on:
  push:
    branches:
      - main
env:
  CI: true
  SSH_PORT: 22

jobs:
  send-noti-on-start:
    runs-on: ubuntu-latest
    name: Send noti to telegram on
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RECEIVER }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Start deploy Nested Notation to production 🚀
            Commit message ✨: ${{ github.event.head_commit.message}}
            Commited by 🚀: ${{ github.event.head_commit.author.name}}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  deploy:
    runs-on: ubuntu-latest
    needs: send-noti-on-start
    continue-on-error: true
    steps:
      - name: Pull code and restart pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PRO }}
          username: ${{ secrets.SSH_USERNAME_PROD }}
          port: 22
          password: ${{ secrets.SSH_PASSWORD_PRO }}
          script: |
            whoami
            pwd
            cd nestednotation
            git pull origin main
            npm install
            pm2 start ecosystem.config.js -f
  send-noti-on-complete:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Telegram Message
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RECEIVER }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Deploy Nested Notation to production successfully 🚀
            See changes:
      - name: Send Telegram Message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RECEIVER }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Deploy Nested Notation to dev failed ❌
